name: unihub
description: "A campus-based e-commerce platform for university students in Africa."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI + Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_image_compress: ^2.1.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.4
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.0.0
  timeago: ^3.6.1
  appinio_swiper: ^2.1.1
  confetti: ^0.8.0
  animated_text_kit: ^4.3.0
  flutter_animate: ^4.5.2    
  google_generative_ai: ^0.4.0
  uuid: ^4.3.3
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  
  # State management
  provider: ^6.1.2
  
  # Backend (Supabase)
  supabase_flutter: ^2.5.6
  
  # Navigation
  go_router: ^14.2.0
  
  # HTTP & API
  http: ^1.2.2
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  
  # Payment
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

dependency_overrides:
  intl: ^0.18.1
  http: ^1.2.2